### ISSUE TITLE
Dialing failed when connecting 4 nodes locally to abci

### ISSUE THREAD

**Issue by gauthamzz** [tendermint/tendermint#3178]
**Tendermint version** : 0.28.1-07263298

**ABCI app** : https://github.com/gauthamzz/vimana/blob/master/tendermint/app.py

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Install tools**:
- **Others**:

**What happened**:

Created a docker-compose to connect to 4 nodes using abci written in python. 
``` 
version: '3'

services:
  node0:
    container_name: tmnode0
    image: "tendermint/localnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command:  node --proxy_app=tcp://abci0:26658 --consensus.create_empty_blocks=false
    # command: node --proxy_app=kvstore
    networks:
      localnet:
        ipv4_address: 192.167.10.2
    extra_hosts:
      - "dockerhost:192.167.0.1"

  node1:
    container_name: tmnode1
    image: "tendermint/localnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command:  node --proxy_app=tcp://abci1:26658 --consensus.create_empty_blocks=false
    # command: node --proxy_app=kvstore
    depends_on:
      - abci1
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: tmnode2
    image: "tendermint/localnode"
    environment:
      - ID=2
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    command:  node --proxy_app=tcp://abci2:26658 --consensus.create_empty_blocks=false
    # command: node --proxy_app=kvstore
    depends_on:
      - abci2
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: tmnode3
    image: "tendermint/localnode"
    environment:
      - ID=3
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    command:  node --proxy_app=tcp://abci3:26658 --consensus.create_empty_blocks=false
    # command: node --proxy_app=kvstore
    depends_on:
      - abci3
    networks:
      localnet:
        ipv4_address: 192.167.10.5
  abci0:
    container_name: abci0
    image: "abcinode"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: python3 vimana/tendermint/app.py
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    container_name: abci1
    image: "abcinode"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: python3 vimana/tendermint/app.py
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    container_name: abci2
    image: "abcinode"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: python3 vimana/tendermint/app.py
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    container_name: abci3
    image: "abcinode"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: python3 vimana/tendermint/app.py
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
```

It works fine with `kvstore` app.

**What you expected to happen**:

The nodes were supposed to send transactions with each other, but only initial state is committed .
**Have you tried the latest version**: yes/no
yes
**How to reproduce it** (as minimally and precisely as possible):

This is the https://github.com/gauthamzz/vimana/blob/master/docker/abci.Dockerfile abci dockerfile. I used the same tendermint/localnet.

`make localnet-start`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

`
tmnode1  | E[21016-01-21|09:26:55.506] Dialing failed                             module=pex addr=cfe71f7e4c5c27d0fc4e2f16d10294c47a9c8cbb@192.167.10.3:26656 err="self ID<cfe71f7e4c5c27d0fc4e2f16d10294c47a9c8cbb>" attempts=0
tmnode0  | E[21016-01-21|09:26:55.997] Dialing failed                             module=pex addr=a619771b0df58e531bd847803376de1b880491bc@192.167.10.2:26656 err="self ID<a619771b0df58e531bd847803376de1b880491bc>" attempts=0
tmnode3  | E[21016-01-21|09:26:56.674] Dialing failed                             module=pex addr=4fff6add7b50fe166b437053eae5d036a47b4b5d@192.167.10.5:26656 err="self ID<4fff6add7b50fe166b437053eae5d036a47b4b5d>" attempts=0
tmnode2  | E[21016-01-21|09:27:24.501] Dialing failed                             module=pex addr=9b17a1d854ef727fdc8294f35301b2b56ce33cbe@192.167.10.4:26656 err="self ID<9b17a1d854ef727fdc8294f35301b2b56ce33cbe>" attempts=0
`
**Config (you can paste only the changes you've made)**:

**node command runtime flags**:
`node --proxy_app=tcp://abci3:26658 --consensus.create_empty_blocks=false`

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
One a single node it was working fine, with the tendermint and abci. 
I am just trying to run an abci and tendermint node on localcluster. If i am doing wrong way, any links will help. Thank :smile_cat:
