### ISSUE TITLE
Unable to connect to bigchaindb

### ISSUE THREAD

**Issue by angad012** [tendermint/tendermint#3267]
Tendermint version: 0.22.8

BigchainDB : __version__ = '2.0.0b7'

**Environment**: Kubernetes ( google cloud platform and suse caasp ) :

**What happened**: I am using tendermint 0.22.8 with Bigchaindb 2.0 with mongodb as a persistence for bigchaindb . i have deployed the cluster on kubernetes with persistence ( persistenceVolumeclaims)for tendermint and mongodb . After deploying the pods and making a transaction ( via bigchaindb) , i can see the block height increased to 3 in bigchain logs . Now i try to restart my tendermint pod and see the follwoing logs :

<img width="1224" alt="tendermint" src="https://user-images.githubusercontent.com/35956397/52402713-48cf9b80-2ac5-11e9-9e1d-8ebeabc00709.png">

**What you expected to happen**: Tendermint to retrieve correct apphash and start the container again 

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible): Deploy the containers ( pods) for mongodb , bigchaindb and tendermint . Do a few transactions and restart tendermint container

**Comment by melekes** [comment]
Did you make sure `/tendermint/data/blockstore.db/LOG` exist on pods? How do you mount volumes?

**Comment by thanethomson** [comment]
Was going to ask, @angad012, could you perhaps post your K8s config here?

**Comment by thanethomson** [comment]
I don't see you mounting the `/tendermint/data` directory in your `statefulset.yaml` file:

```yaml
#################################################################################
# This YAML file desribes a StatefulSet with a service for running and exposing #
# a Tendermint instance. It depends on the tendermint-config-db-claim           #
# and tendermint-db-claim k8s pvc.                                              #
#################################################################################

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: tm-instance-1-ss
spec:
  serviceName: tm-instance-1
  replicas: 1
  template:
    metadata:
      name: tm-instance-1-ss
      labels:
        app: tm-instance-1-ss
    spec:
      restartPolicy: Always
      volumes:
        - name: tm-config-volume
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
          configMap:
            name: tm-config
        - name: tm-config
          emptyDir: {}
      initContainers:
        - name: copy-configs
          image: busybox
          command: ['sh', '-c', 'cp /tmp/tm-config-volume/* /tendermint/config/ 2>/dev/null || true;']
          volumeMounts:
            - name: tm-config-volume
              mountPath: /tmp/tm-config-volume/
            - name: tm-config
              mountPath: /tendermint/config/
      containers:
  #Tendermint container
      - name: tendermint
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        volumeMounts:
          - name: tm-config-volume # configMaps
            mountPath: /tmp/tm-config-volume/
          - name: tm-config
            mountPath: /tendermint/config/
        # Resource constraint on the pod, can be changed
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.ports.p2p.containerPort }}
          name: {{ .Values.ports.p2p.name }}
        - containerPort: {{ .Values.ports.rpc.containerPort }}
          name: {{ .Values.ports.rpc.name }}
```

I only see a mount for your `/tendermint/config` folder. The error you're getting is because, after restart, the `/tendermint/data` folder (which is effectively ephemeral now) is gone.

Also, is there any particular reason why you'd want to use that `initContainers` section? I'd just mount the `/tendermint/config` folder directly from the PVC.
