### ISSUE TITLE
docker: Integrate user-defined ABCI application with localnet using docker compose - CONNECTION FAILED B/W Node and ABCI containers

### ISSUE THREAD

**Issue by srinathLN7** [tendermint/tendermint#4074]
![Pic1](https://user-images.githubusercontent.com/45759699/69336120-663db280-0c5e-11ea-8081-2a6268039b40.PNG)
![Pic2](https://user-images.githubusercontent.com/45759699/69336127-6938a300-0c5e-11ea-9e41-40e64ec14194.PNG)

I am trying to integrate my own ABCI-application with the localnet.  The Dockerfile in my abci file directory

```
version: '3'

services:
  abci0:
    container_name: abci0
    image: "abci-image"
    build:
      context: .
      dockerfile: ./samplePOC/Dockerfile
    networks:
      localnet:
        ipv4_address: 192.167.10.6


  node0:
    container_name: node0
    image: "tendermint/localnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci0:26658
    depends_on:
      - abci0
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  
  
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
```

Both the nodes and the abci- containers are built successfully. The ABCI server is started successfully and the nodes are trying to make connections. However the main problem is that the I see the two are not able to communicate with each other. 

I get the following error:

`node0  |E[2019-10-29|15:14:28.525] abci.socketClient failed to connect to tcp://abci0:26658.  Retrying... module=abci-client connection=query err="dial tcp 192.167.10.6:26658: connect: connection refused"`

Can someone please help me here? 

 
![Pic1](https://user-images.githubusercontent.com/45759699/69328325-57033880-0c4f-11ea-8b4a-0d9c58094c19.PNG)
![Pic2](https://user-images.githubusercontent.com/45759699/69328333-59fe2900-0c4f-11ea-84a8-0d7aa3dab56c.PNG)

**Comment by melekes** [comment]
What network are you using? bridge?

```
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
```

**Comment by srinathLN7** [comment]
@melekes  Yes, exactly the same config as your specified above as specified in the documentation. Using bridge.

``` 
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
```

**Comment by melekes** [comment]
>     ports:
      - "26658:26658"

are you allocating the same port for every abci app (0,1,2,3)?

**Comment by srinathLN7** [comment]
@melekes 

if I allocate the same ports from host to container as in here 
```
abci0:
    container_name: abci0
    image: "abci-image"
    volumes:
      - $GOPATH/src/samplePOC:/go/src/samplePOC
    ports:
      - "26658:26658"
    build:
      context: .
      dockerfile: $GOPATH/src/samplePOC/
    command:  /go/src/samplePOC/samplePOC
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    container_name: abci1
    image: "abci-image"
    volumes:
      - $GOPATH/src/samplePOC:/go/src/samplePOC
    ports:
      - "26658:26658"
    build:
      context: .
      dockerfile: $GOPATH/src/samplePOC/
    command:  /go/src/samplePOC/samplePOC
    networks:
      localnet:
        ipv4_address: 192.167.10.7
```

I get the following error 
` ERROR: for abci0  Cannot start service abci0: driver failed programming external connectivity on endpoint abci0 (fe4b7cf3e3ef00626109ed5385685f9a112bf599dcc02155d42f7ca0b9e44b36): Bind for 0.0.0.0:26658 failed: port is already allocated`

I tried allocating different port in host machine to same port in container i.e, say in abci1
we have 
`ports:
  - 26665:26658`

and still doesn't do anything.  The ABCI server is just printing the output but its not listening for any connections. Could you please help here?
