### ISSUE TITLE
Using tm-monitor tool via docker

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [tendermint/tendermint#4395]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.32.8-759ccebe

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I am trying to implement tendermint tool tm-monitor using the code
`docker run -it --rm -p "46670:46670" --link=tm tendermint/monitor tm:46657` on an alternate window. But I get an error
`docker: Error response from daemon: driver failed programming external connectivity on endpoint determined_poitras (965eb47039982d613eebbd01afee03e9416b90076e5aacba6e985a3d52f5d96c): Error starting userland proxy: listen tcp 0.0.0.0:46670: bind: address already in use`

**What you expected to happen**:

See the statistics of the transactions as mentioned in the tendermint documentation.
**Have you tried the latest version**: yes/no yes

**How to reproduce it** (as minimally and precisely as possible):
`docker run -it --rm -v "/tmp:/tendermint" tendermint/tendermint init
docker run -it --rm -v "/tmp:/tendermint" -p "46657:46657" --name=tm tendermint/
˓ → tendermint node --proxy_app=kvstore
docker run -it --rm -p "46670:46670" --link=tm tendermint/monitor tm:46657`
**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
`docker: Error response from daemon: driver failed programming external connectivity on endpoint determined_poitras (965eb47039982d613eebbd01afee03e9416b90076e5aacba6e985a3d52f5d96c): Error starting userland proxy: listen tcp 0.0.0.0:46670: bind: address already in use`
**Config (you can paste only the changes you've made)**:
No changes
**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
it seems the port is already in use for something else. 

we also deprecated tm-monitor recently and recommend using the built-in Prometheus metrics. This can be turned on in the config.toml file. this is also what the [testnets repo uses] (https://github.com/interchainio/testnets/tree/master/monitor)

**Comment by Anjana-Prabhakar** [comment]
@marbar3778 Thanks for the help. I enabled the Prometheus metrics in config file and started the tendermint network.  I tried to check the metrics using command:
`curl http://localhost:26660/metrics` but it gave me a `404 page not found error`.

**Comment by marbar3778** [comment]
im not sure what the issue is. it should be available. are you still having this issue?

**Comment by Anjana-Prabhakar** [comment]
I am still facing the issue. I am using the command`make localnet start` to start the network. On the browser I get a page for 

> http://localhost:26660
But there is no attribute metrics in it.

**Comment by melekes** [comment]
Make sure you have prometheus running:

```
prometheus --config.file=prometheus.yml
```

```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1s

    static_configs:
      - targets: ['localhost:26660']
```

I am gonna close this since tm-monitor is no longer supported.
