### ISSUE TITLE
statesync: snapshot discovery not robust enough

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5481]
In the below E2E testnet, the node `validator08` is not able to initially state sync since it can't discover any snapshots, even though there are peers in the network that are generating snapshots. This does seem to clear up eventually - possibly peer propagation is too slow, but worth looking into. Note that the node only has a single persistent peer, which isn't itself producing snapshots, so the node relies on this peer to relay information about other peers to us.

```toml
ipv6 = false
initial_height = 1000

[initial_state]
  initial01 = "a"
  initial02 = "b"
  initial03 = "c"

[validators]

[validator_update]
  [validator_update.0]
    validator01 = 49
    validator02 = 49
    validator03 = 39
    validator04 = 87
    validator05 = 84
    validator06 = 50
  [validator_update.1010]
    validator07 = 41
  [validator_update.1015]
    validator08 = 93

[node]
  [node.full01]
    mode = "full"
    persistent_peers = ["validator08", "validator06", "full02", "validator02", "validator03", "validator01"]
    database = "rocksdb"
    abci_protocol = "builtin"
    privval_protocol = "tcp"
    start_at = 1015
    fast_sync = ""
    state_sync = false
    persist_interval = 1
    snapshot_interval = 3
    retain_blocks = 3
    perturb = ["disconnect"]
  [node.full02]
    mode = "full"
    seeds = ["seed01"]
    database = "boltdb"
    abci_protocol = "unix"
    privval_protocol = "unix"
    start_at = 0
    fast_sync = "v0"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    perturb = []
  [node.seed01]
    mode = "seed"
    seeds = ["seed02", "seed03"]
    database = "badgerdb"
    abci_protocol = "builtin"
    privval_protocol = "file"
    start_at = 0
    fast_sync = "v2"
    state_sync = false
    persist_interval = 1
    snapshot_interval = 3
    retain_blocks = 3
    perturb = []
  [node.seed02]
    mode = "seed"
    seeds = ["seed03", "seed01"]
    database = "goleveldb"
    abci_protocol = "builtin"
    privval_protocol = "file"
    start_at = 0
    fast_sync = "v2"
    state_sync = false
    persist_interval = 0
    snapshot_interval = 3
    retain_blocks = 0
    perturb = []
  [node.seed03]
    mode = "seed"
    seeds = ["seed02", "seed01"]
    database = "rocksdb"
    abci_protocol = "unix"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = ""
    state_sync = false
    persist_interval = 0
    snapshot_interval = 3
    retain_blocks = 0
    perturb = []
  [node.validator01]
    mode = "validator"
    seeds = ["seed02", "seed03"]
    database = "boltdb"
    abci_protocol = "builtin"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = ""
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    perturb = []
  [node.validator02]
    mode = "validator"
    persistent_peers = ["validator01"]
    database = "cleveldb"
    abci_protocol = "unix"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = "v0"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    perturb = []
  [node.validator03]
    mode = "validator"
    seeds = ["seed01", "seed02"]
    database = "boltdb"
    abci_protocol = "tcp"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = "v2"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 0
    retain_blocks = 5
    perturb = []
  [node.validator04]
    mode = "validator"
    seeds = ["seed02"]
    database = "cleveldb"
    abci_protocol = "unix"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = "v2"
    state_sync = false
    persist_interval = 1
    snapshot_interval = 0
    retain_blocks = 5
    perturb = []
  [node.validator05]
    mode = "validator"
    seeds = ["seed03", "seed02"]
    database = "goleveldb"
    abci_protocol = "builtin"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = ""
    state_sync = false
    persist_interval = 0
    snapshot_interval = 0
    retain_blocks = 0
    perturb = []
  [node.validator06]
    mode = "validator"
    seeds = ["seed02", "seed03"]
    database = "cleveldb"
    abci_protocol = "builtin"
    privval_protocol = "file"
    start_at = 0
    fast_sync = "v0"
    state_sync = false
    persist_interval = 1
    snapshot_interval = 3
    retain_blocks = 3
    perturb = ["disconnect"]
  [node.validator07]
    mode = "validator"
    persistent_peers = ["validator03", "validator01", "validator05", "validator02"]
    database = "rocksdb"
    abci_protocol = "tcp"
    privval_protocol = "file"
    start_at = 1005
    fast_sync = "v2"
    state_sync = true
    persist_interval = 5
    snapshot_interval = 0
    retain_blocks = 5
    perturb = []
  [node.validator08]
    mode = "validator"
    persistent_peers = ["validator03"]
    database = "cleveldb"
    abci_protocol = "builtin"
    privval_protocol = "tcp"
    start_at = 1010
    fast_sync = ""
    state_sync = true
    persist_interval = 0
    snapshot_interval = 0
    retain_blocks = 0
    perturb = []
```
