### ISSUE TITLE
Can't connect to secure endpoints through websocket

### ISSUE THREAD

**Issue by yoongbok-lee** [tendermint/tendermint#9316]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.20

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu
- **Install tools**:
- **Others**: go 1.18, tendermint 

**What happened**:
Can't connect to https RPC endpoint through websocket

**What you expected to happen**:
Can connect to https RPC endpoint through websocket

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

```
package main

import (
	jsonrpcclient "github.com/tendermint/tendermint/rpc/jsonrpc/client"
)

func main() {
	wsc, err := jsonrpcclient.NewWS("https://bd-evmos-testnet-state-sync-node-01.bdnodes.net:26657", "/websocket")
	if err != nil {
		panic(err)
	}
	err = wsc.Start()
	if err != nil {
		panic(err)
	}
}

```

or making the client `rpcclient.New(.,..` doesn't help. errors out with `websocket: bad handshake`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

panic: websocket: bad handshake

**Config (you can paste only the changes you've made)**:

no config change

**node command runtime flags**:

no flags

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by l-wegner** [comment]
**Tendermint version**: 
v0.34.19
**ABCI app** (name for built-in, URL for self-written if it's publicly available): 
not publicly available

**Environment**:

- **OS** (e.g. from /etc/os-release): locally: ubuntu/20.04 container base image: debian:10.11-slim
- **Install tools**:
- **Others**: go 1.19, ignite cli v0.23.0

**What happened**:
Can't connect to https RPC endpoint through websocket using `github.com/tendermint/tendermint/rpc/jsonrpc/client/http.go/HTTP.New[WithClient](remote,endpoint,[client])`.

**What you expected to happen**:
Be able to subscribe to events to events after calling github.com/tendermint/tendermint/rpc/jsonrpc/client/http.go/HTTP.Start()

**Have you tried the latest version**: 
on client side only, yes (v0.35.9)

**How to reproduce it** (as minimally and precisely as possible):
See [Test suite](#Test-suite) code block.

**Config** (you can paste only the changes you've made):
config.toml
```toml
[rpc]
cors_allowed_origins = ["*"]
laddr = "tcp://0.0.0.0:26657"
```
**node command runtime flags**:
`chaind start --home "$HOME_FOLDER"`

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**:
not applicable

**Anything else we need to know**:
I experience the similar, with our test nodes.
I tried several port and protocol permutations with the [HTTP-client](https://github.com/tendermint/tendermint/blob/v0.34.19/rpc/client/http/http.go#L131) .
I hoped it's just a not-straight-forward setup. I created the test suite for it ([output at pastebin.com (1 year retention)](https://pastebin.com/qV8XqScx)).
No test succeeded, when using our host, because of our ingress (see [our node](#Our-test-node)) enforcing TLS.
But only these tests succeeded with the host of the OP:
- `http_client:_http:26657_and_ws_client:_http:26657`
- `http_client:_https:26657_and_ws_client:_http:26657`


### Test suite
```go
package main

import (
  goctx "context"
  "fmt"
  rpchttp "github.com/tendermint/tendermint/rpc/client/http"
  jsonrpcclient "github.com/tendermint/tendermint/rpc/jsonrpc/client"
  "reflect"
  "testing"
  "time"
)

const (
  endpoint     = "/websocket"
  hostname     = "bd-evmos-testnet-state-sync-node-01.bdnodes.net"
  httpAddress  = "http://" + hostname + ":"
  httpsAddress = "https://" + hostname + ":"
  wsAddress    = "ws://" + hostname + ":"
  wssAddress   = "wss://" + hostname + ":"
)

func httpNewWithClient(httpRemote string, wssRemote string) (errStatus error, errSocket error) {
  http, err := jsonrpcclient.DefaultHTTPClient(httpRemote)
  if err != nil {
    panic(err)
  }
  http.Timeout = time.Duration(2) * time.Second
  // with v0.35.9 the paramter endpoint has to be removed
  // rpc, err := rpchttp.NewWithClient(wssRemote, http)
  rpc, err := rpchttp.NewWithClient(wssRemote, endpoint, http)
  if err != nil {
    panic(err)
  }
  return tryRequests(rpc)
}

func tryRequests(rpc *rpchttp.HTTP) (errStatus error, errSocket error) {
  errSocket = nil
  errSocket = nil
  _, errStatus = rpc.Status(goctx.Background())
  errSocket = rpc.Start()
  if errSocket == nil {
    defer func() { _ = rpc.Stop() }()
  }
  return
}

type httpNewWithClientCaseArgs struct {
  httpRemote string
  httpPort   string
  wssRemote  string
  wsPort     string
}
type httpNewWithClientCase struct {
  name          string
  args          httpNewWithClientCaseArgs
  wantStatusErr error
  wantSocketErr error
}

func PermuteTestCases(addresses map[string]string, ports []string) []httpNewWithClientCase {
  var testCases []httpNewWithClientCase
  for httpUrlName, httpUrl := range addresses {
    for _, httpPort := range ports {
      for wsUrlName, wsUrl := range addresses {
        for _, wsPort := range ports {
          testCases = append(testCases,
            httpNewWithClientCase{
              fmt.Sprintf("http client: %s:%s and ws client: %s:%s", httpUrlName, httpPort, wsUrlName, wsPort),
              httpNewWithClientCaseArgs{
                httpUrl,
                httpPort,
                wsUrl,
                wsPort,
              },
              nil,
              nil,
            })
        }
      }
    }
  }
  return testCases
}

func Test_httpNewWithClient(t *testing.T) {
  addresses := map[string]string{
    "http":  httpAddress,
    "https": httpsAddress,
    "ws":    wsAddress,
    "wss":   wssAddress,
  }
  ports := []string{"443", "26657"}
  for _, tt := range PermuteTestCases(addresses, ports) {
    t.Run(tt.name, func(t *testing.T) {
      statusErr, socketErr := httpNewWithClient(tt.args.httpRemote+tt.args.httpPort, tt.args.wssRemote+tt.args.wsPort)
      if !reflect.DeepEqual(statusErr, tt.wantStatusErr) {
        t.Errorf("httpNewWithClient() statusErr = %v, want %v", statusErr, tt.wantStatusErr)
      }
      if !reflect.DeepEqual(socketErr, tt.wantSocketErr) {
        t.Errorf("httpNewWithClient() socketErr = %v, want %v", socketErr, tt.wantSocketErr)
      }
    })
  }
}
```
### Our test node
On the other hand, I succeed to connect to our node at "wss://_node_:443/websocket" when using the "Simple Web Socket Client" chrome extension.
Our Node runs in Kubernetes with an ingress like this:
### ingress.yaml of our node
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    app.kubernetes.io/instance: testnet-validator-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: validator1
    app.kubernetes.io/version: <redacted>
    helm.sh/chart: validator-node-0.1.0
  name: testnet-validator-1-validator1-ingress
  namespace: <redacted>
spec:
  rules:
    - host: validator1-tdmt-rpc.<redacted>
      http:
        paths:
          - backend:
              service:
                name: testnet-validator-1-validator1-service
                port:
                  number: 26657
            path: /(.*)
            pathType: Prefix
  tls:
    - hosts:
        - validator1-tdmt-rpc.<redacted>
      secretName: tls-secret
```
